version: "3.8"
services:
  mongo_db:
    container_name: davkart_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    networks:
      - database-network

  api:
    build: .
    container_name: davkart_c
    ports:
      - "4000:4000"
    volumes:
      - .:/src
      - /src/node_modules
    depends_on:
      - mongo_db
    networks:
      - database-network
    environment:
      - LOCAL_MONGO_URL= ${ROOT_MONGO_URL}
      - MONGO_URL= ${MONGO_URL}
      - NODE_ENV= ${NODE_ENV}
      - PORT= ${PORT}
      - JWT_SECRET= ${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME= ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY= ${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET= ${CLOUDINARY_API_SECRET}
      - MAIL_SERVICE_URL= ${MAIL_SERVICE_URL}

networks:
  database-network:
    name: database-network
    driver: bridge
